---
title: '한국 프로야구 자료를 가지고 가공하는 강좌를 만드는 프로젝트 # 1'
output:
  html_notebook: default
  html_document: default
  pdf_document: default
  word_document: default
---

안녕하세요. lopes 박자영입니다.
저번 강좌에서는 for문을 이용하여 날짜가 들어있지 않은 항목에 날짜와 시간을 넣는 법을 배웠었죠?

이번에는 자료를 세분화하기 위한 함수만들기를 배워보겠습니다. 
여기서 배우게 될 기존 함수는 ifelse, grep, gsub, strsplit 4가지 입니다.
그리고 이러한 기존 함수를 이용해서 새로운 함수를 만들어 볼거에요~!

일단 우리는 자료를 세분화하기 위해서 왜 함수를 만들어야 하는지를 이해할 필요가 있습니다.
급하게 답을 말하자면, 
R 기존에 있는 함수로 동일한 변수를 연속적으로 바꿀 수 없기 때문에 새로운 함수를 만들필요가 있습니다. 

여기서 자료를 세분화시키는 몇 가지의 기존의 함수를 배울텐데요, 새로운 함수를 만들지 않고 이들을 이용해 하나의 자료를 나누려고 하면, 분명히 어떤 것은 되었다가 안되었다가 하는 딜레마를 겪으 실 수 있을 거에요. ㅠㅠ 지면상 이러한 난관에 봉착하는 과정은 생략할게요. 

그럼 먼저 자료를 세분화 하는 방법을 알아보겠습니다.
여기서 보여드릴 함수는 gsub , strsplit 입니다. 

kbo.2015.3 자료의 경기부분을 예로 들어볼게요~!
(15행에서 18행까지만 예로 사용하겠습니다.)

```{r}
kbo.2015.3$경기[15:18]
```

위의 자료를 보면 경기열에 하나로 뭉쳐있는 문자열을 볼 수 있습니다.
이러한 자료를 아래와 같이 바꾸려고 합니다. 

```

  날짜 원정팀 원정팀_점수 홈팀_점수 홈팀 구장           비고
15        두산           0         9 삼성                    
16          SK           1         9 롯데                    
17                                             경기가 없는 날
18         KIA                       삼성           경기 취소

```


여기서 15행으로 예를 들어 보면,  "두산  0:9  삼성" 을
원정팀 열에 "두산", 원정팀_수 열에 "0", 홈팀_점수 "9", 홈팀 구장 "삼성" 으로 분리한것을 볼 수 있죠. "
또한 18행을 보면 "KIA VS 삼성" 도 "KIA" 와 "삼성"으로 분리된 것을 볼 수 있습니다.

이렇게 분리하기 위해서 우리는 기존의 문자열을 선택해서 분리하는 함수를 이용할 수 있습니다.
원래의 자료에서  15, 16행은 콜론(:)이 있는 반면에 18행에는 VS가 있는 것을 알 수 있는데요,
이들은 우리가 가공할 자료에서 필요없는 문자열이기 때문에 이를 이용하여 분리할수 있는 겁니다.

그런데 여기서 잘 생각해야 하는 것이 행마다 콜론과 VS라는 서로 다른 문자열이 있기 때문에 
이를 따로따로 처리할 것인지 아니면 동시에 처리할 것인지를 고민해볼 필요가 있습니다.

저는 여기서 콜론(:)과 VS를 " "(빈공간) 으로 바꿔서 한번에 분리하는 방법을 선택하겠습니다.
우선 콜론(:)과 VS를 " "(빈공간)으로 바꿀 수 있는 gsub 함수를 알아보겠습니다.

gsub은 특정 문자열을 선택하여 지정된 문자로 바꾸는 함수입니다. 

사용 방법은 다음과 같습니다.

```{R}
x <-"디오는 내 남편이다."
x
```

```{R}
x <- gsub("디오", "박보검", x)
x
```

디오가 박보검으로 바뀌었죠?
다시 말해서 gsub("선택할 문자열", "바꿀 문자열", 변수) 이렇게 사용하면 되는 겁니다!

그럼 kbo를 gsub을 이용해서 바꾸어 보겠습니다. 

```{R}

Y <- kbo.2015.3$경기[15:18]
Y <- gsub(":", " ", kbo.2015.3$경기[15:18])
Y
```

콜론(:)이 " " 빈공간으로 바뀌였죠?
이어서 VS도 " " 빈공간으로 바꿔 보겠습니다.

```{R}
Y <- kbo.2015.3$경기[15:18]
Y <- gsub("VS", " ", kbo.2015.3$경기[15:18])
Y
```

4행을 보시면 VS가 " " 을 바뀐것을 확인할 수 있습니다. 그런데 콜론이 다시 돌아왔네요 ㅎㅎ

그래서 함수를 새로 만들 필요가 있는 겁니다. 

이제 함수를 만들기에 앞서 콜론과 VS를 " " 빈공간으로 바꾸었는데요, 이 " "빈공간으로 문자열을 분리하는 방법부터 보겠습니다. 

여기서 우리는 strsplit 함수를 사용할 수 있습니다.

strsplit 함수는 특정 문자열을 선택해서 그것으로 하나의 문자를 분리하는 함수 입니다.

사용방법은 다음과 같습니다.

```{R}
x <- "디오는 내 남편이다. 그리고 박보검은 내 남편이다."
x
```

```{R}
x <- strsplit(x, "그리고")
x
```
한문장이 두개로 분리된 것을 확인할 수 있습니다.
다시 말해서 strsplit(변수, "분리를 위해서 선택한 문자열") 이렇게 사용하면 되는 겁니다!

kbo를 가지고 분리해보는 것은 함수를 만들고 나서 해보기로 하고
이제 우리가 원하는 자료를 만들 수 있는 함수를 만드는 방법을 알아보겠습니다. 

R에서 모든 함수는 이름, 코드, 인수라는 3가지 기본요소를 갖습니다. 
자신만의 함수를 만들 때는 이 요소들을 고려해서 R객체에 이것들을 저장하는데
이때 function이라는 함수를 사용합니다. 
먼저 function()를 호출하고 바로 뒤에 중괄호 {}를 사용합니다. 
그리고 중괄호 안에 R코드로 함수를 만들어 넣으면 됩니다. 

또한 함수는 우리에게 값을 되돌려주기 위한 메커니즘이 필요합니다. 
그래서 return 명령어를 사용하여 명확하게 리턴되어야 할 값을 지정할 수 있습니다. 
이 경우 함수는 반드시 종료되어야 합니다. 

앞에서 배운 것을 가지고 예를 들어 보겠습니다.
```{R}
x <- "디오:박보검:크러쉬:나플라는:나의:남편들이다."
Husbands <- function(x){
  x <- gsub(":"," ",x)
  x <- strsplit(x, " ")
  print(x)
  return(x)
}
Husbands(x)
```

자 이런식으로 응용하시면 됩니다~!
그럼 이번엔 kbo 파일을 가지고 원래 목적인 자료 세분화를 위한 함수를 만들어 보겠습니다.
여기서 이용할 또 다른 함수는 ifelse와 grep 함수에요~!

먼저, ifelse 함수는 어떤 특정한 조건을 만족시킬때, 우리가 원하는 것을 수행하게끔 하는 함수입니다. 

예를 볼까요?

```{R}
Husbands <-c("디오", "크러쉬", "혁오", "박보검")
ifelse(Husbands == "크러쉬", "yes", "no")
```

자 이렇게 보시는 거와 같이 저의 남편들(Husbands)이란 변수 안에서 크러쉬가 있다면
yes를 아니면 no를 말해달라고 명령하였더니 
남편들(Husbands) 이란 변수 안에서 크러쉬가 맞으면 yes를 아니면 no를 반환되었습니다! 

즉, 다시 말해서 
ifelse(변수 == 찾는 조건, "조건을 만족 시킬때 반환할 값", "조건을 만족 시키지 못할때 반환할 값") 이렇게 사용하는 겁니다.

이제 우리는 이 ifelse함수를 이용해서 kbo 함수를 만들 수 있습니다.
그러면 이 ifelse함수가 왜 필요한지 알아야 겠죠~?

아까 보았듯이 kbo 원자료는 행마다 문자열이 모두 같지 않습니다.
다시 보려드리면

```{R}
kbo.2015.3$경기[15:18]
```

이처럼 어떤 행에는 콜론(:) 있고, 어떤 행에는 "프로야구 경기가 없습니다"와 같은 다른 형식의 문자열이 들어가 있기도 하고, VS가 들어가 있기도 합니다. 
앞서 알려드렸던 함수를 이용해서 이를 나누려고 한다면 모든 행에 함수가 적용이 되기 때문에
"프로야구 경기가 없습니다" 라는 문자열이 분리되거나, VS를 바꾸니 콜론(:)이 다시 생기거나 하게 됩니다. 

그래서 바로 ifelse함수를 이용해서 특정 조건을 만족시킬때 그것을 바꾸라고 명령하려고 하는 겁니다. 그러면 하나의 변수로 원하는 것만 선택적으로 작업할 수 있게 되겠죠! 

이어서 grep 함수도 알아보겠습니다. 

grep 함수는 변수에서 우리가 원하는 특정 패턴을 찾아서 그 위치를 출력하는 함수입니다.

예를 보겠습니다.
```{R}
y <-c("박보검", "디오", "크러쉬")
grep("박보검", y)
```

"박보검"이란 패턴이 하나 있다고 결과가 나옵니다.
한번 더 해볼까요?

```{R}
y <-c("박보검", "디오", "크러쉬", "박보검")
grep("박보검", y)
```

첫번째와 4번째에 "박보검"이란 패턴이 있다고 알려줍니다.

다시 말해서 grep(찾고자하는 패턴, 변수) 이렇게 사용하는 겁니다.

자 이제 여기까지 자료를 제가 원하는 방식으로 세분화 하기 위한 함수를 배웠습니다.
우리가 위에서부터 배운 기존의 함수는 모두 gsub, strsplit, 함수만들기, ifelse, grep 인거죠!

그럼 본격적으로 코드를 만들어 보겠습니다. 

```
 ifelse(grep(":", x)== 1, temp <- gsub(":"," ",x), ":이 없으면 경기취소 입니다")
 ifelse(grep("VS", x)== 1, temp <- gsub("VS"," ",x), "VS가 없으면 경기취소 입니다")
 temp <- strsplit(temp, " ")
```

자 이렇게 만들었습니다. 
첫 번째 줄을 볼까요~?

x라는 변수 안에 콜론 ":" 이 하나 있으면  gsub을 이용해서 콜론을":"  빈공간" "으로 바꿔서 temp에 넣고 ,  콜론":"이 없으면 ":이 없으면 경기취소 입니다" 를 반환하라는 말입니다. 

두 번째 줄도 마찬가지로 x라는 변수 안에 "VS"가 하나 있으면 "VS"를 빈공간" " 으로 바꿔서 temp에 넣고, "VS"가 없으면 "VS가 없으면 경기취소 입니다"를 반환하라는 말인거죠~

세번째 줄은 조건을 만족시킬때 반환하라고 명령한 값을 넣은 temp를 빈공간" "으로 분리하라는 말입니다. 

이제 이 함수들을 위에서 배운 큰 함수 function(){} 에 넣으면 되는거죠~!
완성된 함수를 볼까요? 


```{R}
kbo.test <- function(x){   
   temp <- x   
   ifelse(grep(":", x)== 1, temp <- gsub(":"," ",x), ":이 없으면 경기취소 입니다")  ## ":"이 있으면, ":"을 " "로 바꿔줍니다. 
   ifelse(grep("VS", x)== 1, temp <- gsub("VS"," ",x), "VS가 없으면 경기취소 입니다")  ## "VS"가 있으면, "VS" 를 " "로 바꿔줍니다. 
   temp <- strsplit(temp, " ")  ## " "로 쪼개줍니다.  
   ## print(temp)   
   ifelse(length(temp[[1]])== 3, temp1 <- data.frame(날짜 = "", 원정팀 = "", 원정팀_점수 = "", 홈팀_점수 = "", 홈팀 = "", 구장 = "", 비고 = "경기가 없는 날"), temp1 <- data.frame(날짜 = "", 원정팀 = temp[[1]][1], 원정팀_점수 = temp[[1]][3], 홈팀_점수 = temp[[1]][4], 홈팀 = temp[[1]][6], 구장 = "", 비고 = "" ))   
   ifelse(temp1$홈팀_점수 == "" & temp1$비고 == "", temp1$비고 <- "경기 취소", temp1) 
   ## 쪼개진 결과가 3개이면, 비고에 "경기가 없는 날"을 넣어줍니다. 그렇지 않은 결과는 그대로 리턴해줍니다. 
   ## 홈팀점수가 없고 비고가 비어있으면, 비고에 "경기취소"를 넣어줍니다. 
   return(temp1)   
 } 
lapply(kbo.2015$경기, kbo.test) 
  ## lapply함수를 통해서 각 행별로 함수를 실행시킨다.  
  ## 함수는 각 행을 한 행짜리 데이터 프레임에 담고 그 한행짜리 데이터 프레임들을 리스트에 저장한다. 
kbo.temp <- do.call(rbind,(lapply(kbo.2015$경기, kbo.test))) 
kbo.2015 <- cbind(kbo.2015, kbo.temp)
dim(kbo.2015)
```

완성된 함수가 좀 복잡하죠?
위에서 배운것 이외에 추가된 것들은 데이터 프레임을 만들고 여러 파일들을 하나로 붙이는 함수인데요,
이것들은 앞으로 계속되는 강좌에서 배우실 수 있습니다.  그래서 여기서는 따로 언급하지 않을게요. 
한번에 많은것을 배우면 머리아프잖아요 ^^;

위와 같이 새롭게 만든 함수를 실행하면 아래와 같은 결과를 얻을 수 있게 되는 겁니다.

```

  날짜 원정팀 원정팀_점수 홈팀_점수 홈팀 구장           비고
15        두산           0         9 삼성                    
16          SK           1         9 롯데                    
17                                             경기가 없는 날
18         KIA                       삼성           경기 취소

```

여기까지 자료를 세분화 하기 위한 함수만들기를 알아보았습니다.
기본적인 함수만들기를 통해서 R의 재미를 더욱 키우시길 바라면서 이만 강좌를 마치겠습니다. 다음 강좌에서 봐요~  총총ㅊ



write.csv(KBO_4_2014,file="KBO_2014.csv",row.names = FALSE)
